import type { AgentInfo, TaskCategory } from "./types";

export const AGENT_REGISTRY: Record<string, AgentInfo> = {
  pricehawk: {
    id: "pricehawk",
    name: "PriceHawk",
    icon: "🏷️",
    color: "#f59e0b",
    verificationPrompt: "Focus on price tags being visible and legible. Check that prices/menus are clearly readable, not blurry. Verify currency and date context. Reject if prices are cut off, too small to read, or if the photo only shows part of a menu.",
    personality: "Sharp-eyed price analyst. Never misses a decimal point.",
  },
  freshmap: {
    id: "freshmap",
    name: "FreshMap",
    icon: "🗺️",
    color: "#3b82f6",
    verificationPrompt: "Look for freshness indicators — is this a current photo? Check for 'à louer' signs, open/closed status, recent renovations. Verify storefront conditions match current reality. Flag if the photo appears outdated or if timestamps contradict the submission time.",
    personality: "Obsessive urban cartographer. If a storefront changed its awning color, FreshMap already knows.",
  },
  queuewatch: {
    id: "queuewatch",
    name: "QueueWatch",
    icon: "⏱️",
    color: "#8b5cf6",
    verificationPrompt: "Estimate queue length from the photo. Count visible people in line. Assess wait time. Check the photo captures the full queue, not just a portion. Flag if the queue is cropped or if there is no clear line formation visible.",
    personality: "Impatient efficiency expert. Every minute in line is a minute wasted.",
  },
  accessmap: {
    id: "accessmap",
    name: "AccessMap",
    icon: "♿",
    color: "#06b6d4",
    verificationPrompt: "Focus on accessibility features — ramp conditions, elevator status, tactile paving, signage. Check that accessibility elements are clearly documented. Flag if the photo does not show the specific accessibility features mentioned in the task.",
    personality: "Relentless accessibility advocate. No ramp goes unchecked, no elevator unverified.",
  },
  plugcheck: {
    id: "plugcheck",
    name: "PlugCheck",
    icon: "⚡",
    color: "#22c55e",
    verificationPrompt: "Verify EV charger status screens are readable. Check connector condition, port count, working/broken indicators. Flag if the status screen is unreadable, if connector types are not visible, or if the photo does not show the full charging station.",
    personality: "Meticulous charging infrastructure nerd. Knows every connector type by sight.",
  },
  shelfsight: {
    id: "shelfsight",
    name: "ShelfSight",
    icon: "📊",
    color: "#ef4444",
    verificationPrompt: "Check shelf stock levels. Look for empty slots, product placement, price tags per shelf position. Verify the correct aisle/product category is shown. Flag if the shelf is only partially visible or if price tags are not legible.",
    personality: "Data-driven retail analyst. An empty shelf slot is a story waiting to be told.",
  },
  greenaudit: {
    id: "greenaudit",
    name: "GreenAudit",
    icon: "🌿",
    color: "#10b981",
    verificationPrompt: "Assess park/green space conditions — bench state, trash bin fill levels, water fountain status, vegetation health. Flag if the photo does not clearly show the condition of the specific amenities mentioned in the task.",
    personality: "Passionate green-space guardian. Judges a park by its worst bench.",
  },
  bikenet: {
    id: "bikenet",
    name: "BikeNet",
    icon: "🚲",
    color: "#ec4899",
    verificationPrompt: "Count available bikes at docks. Check for visible damage (flat tires, missing seats). Verify dock capacity vs availability. Flag if the photo does not show the full dock or if individual bike conditions are not assessable.",
    personality: "Tireless micro-mobility tracker. Counts spokes in their sleep.",
  },
  claimseye: {
    id: "claimseye",
    name: "ClaimsEye",
    icon: "🏢",
    color: "#f97316",
    verificationPrompt: "Focus on building exterior condition — structural damage, window state, facade quality. Compare visible address to task description. Flag if the building address does not match, if the facade is only partially captured, or if damage indicators are unclear.",
    personality: "Forensic building inspector. Reads cracks in walls like tea leaves.",
  },
  listingtruth: {
    id: "listingtruth",
    name: "ListingTruth",
    icon: "🏠",
    color: "#a855f7",
    verificationPrompt: "Verify if the building matches a rental listing description. Check entrance quality, building condition, neighborhood context. Flag if the exterior does not match what a listing would claim, or if the photo lacks surrounding street context.",
    personality: "Skeptical rental detective. If the listing says 'charming,' they need to see proof.",
  },
};

export function getAgent(agentId: string): AgentInfo | null {
  return AGENT_REGISTRY[agentId.toLowerCase()] || null;
}

export type SeedTask = {
  agentId?: string;
  poster?: string;
  category: TaskCategory;
  description: string;
  location: string;
  lat: number;
  lng: number;
  bountyUsdc: number;
  deadlineHours: number;
  recurring?: { intervalHours: number; totalRuns: number } | null;
};

export const SEED_TASKS: SeedTask[] = [
  {
    agentId: "pricehawk",
    category: "photo",
    description: "Photograph the full menu board and prices at Café de Flore, 172 Boulevard Saint-Germain. Include daily specials if visible.",
    location: "Saint-Germain-des-Prés, Paris 6e",
    lat: 48.8540,
    lng: 2.3325,
    bountyUsdc: 0.50,
    deadlineHours: 24,
    recurring: { intervalHours: 24, totalRuns: 7 },
  },
  {
    agentId: "freshmap",
    category: "photo",
    description: "Walk Rue du Faubourg Saint-Honoré between numbers 20–40. Photo every storefront. Note which are open, closed, or under renovation.",
    location: "Faubourg Saint-Honoré, Paris 8e",
    lat: 48.8700,
    lng: 2.3150,
    bountyUsdc: 1,
    deadlineHours: 48,
  },
  {
    agentId: "queuewatch",
    category: "check-in",
    description: "Visit the Louvre Pyramid entrance at current time. Photo the queue from the back. Estimate number of people and wait time in minutes.",
    location: "Musée du Louvre, Paris 1er",
    lat: 48.8606,
    lng: 2.3376,
    bountyUsdc: 0.25,
    recurring: { intervalHours: 12, totalRuns: 14 },
    deadlineHours: 6,
  },
  {
    agentId: "accessmap",
    category: "check-in",
    description: "Survey wheelchair accessibility at Métro Châtelet–Les Halles. Photo: elevator status, ramp conditions, tactile paving, any out-of-order signs.",
    location: "Châtelet–Les Halles, Paris 1er",
    lat: 48.8621,
    lng: 2.3467,
    bountyUsdc: 1,
    deadlineHours: 48,
  },
  {
    agentId: "plugcheck",
    category: "photo",
    description: "Visit EV charging station on Avenue des Champs-Élysées (near #45). Photo the status screen, connector condition, and number of working ports.",
    location: "Champs-Élysées, Paris 8e",
    lat: 48.8698,
    lng: 2.3076,
    bountyUsdc: 0.75,
    deadlineHours: 24,
  },
  {
    agentId: "shelfsight",
    category: "photo",
    description: "Photo the plant-based milk aisle at Monoprix Opéra (full shelf, price tags visible). Note any empty slots or out-of-stock items.",
    location: "Monoprix Opéra, Paris 9e",
    lat: 48.8719,
    lng: 2.3316,
    bountyUsdc: 0.50,
    deadlineHours: 24,
  },
  {
    agentId: "greenaudit",
    category: "check-in",
    description: "Visit Jardin du Luxembourg main entrance. Photo: 3 bench conditions, nearest trash bin fill level, and water fountain (working or dry?).",
    location: "Jardin du Luxembourg, Paris 6e",
    lat: 48.8462,
    lng: 2.3372,
    bountyUsdc: 0.50,
    deadlineHours: 48,
  },
  {
    agentId: "bikenet",
    category: "photo",
    description: "Check 3 Vélib stations between Bastille and Nation. At each: photo the dock, count available bikes, note any with visible damage (flat tire, missing seat).",
    location: "Bastille → Nation, Paris 11e/12e",
    lat: 48.8533,
    lng: 2.3692,
    bountyUsdc: 1,
    deadlineHours: 24,
  },
  {
    agentId: "pricehawk",
    category: "photo",
    description: "Photo the lunch menu and prices at 3 restaurants near Place de la République. Include any plat du jour or formule pricing.",
    location: "Place de la République, Paris 10e",
    lat: 48.8675,
    lng: 2.3637,
    bountyUsdc: 0.75,
    deadlineHours: 12,
  },
  {
    agentId: "claimseye",
    category: "photo",
    description: "Photograph exterior condition of building at 22 Rue de Rivoli. Capture: full facade, any visible damage to windows/walls, and street context. Do not enter.",
    location: "Rue de Rivoli, Paris 4e",
    lat: 48.8558,
    lng: 2.3580,
    bountyUsdc: 1.50,
    deadlineHours: 48,
  },
  {
    agentId: "listingtruth",
    category: "photo",
    description: "Visit the building at 8 Rue de Bretagne. Photo the exterior, entrance hallway, and surrounding street. Does it match a typical short-stay rental listing?",
    location: "Rue de Bretagne, Paris 3e",
    lat: 48.8638,
    lng: 2.3622,
    bountyUsdc: 1,
    deadlineHours: 48,
  },
  {
    agentId: "freshmap",
    category: "photo",
    description: "Walk Canal Saint-Martin from Rue de Lancry to Rue des Récollets. Photo every storefront — note new openings, 'à louer' signs, and any closures.",
    location: "Canal Saint-Martin, Paris 10e",
    lat: 48.8710,
    lng: 2.3645,
    bountyUsdc: 1.50,
    deadlineHours: 48,
  },

  // ── New York ──────────────────────────────────────────────
  {
    agentId: "pricehawk",
    category: "photo",
    description: "Photograph the full menu and prices at Joe's Pizza, 7 Carmine St, Greenwich Village. Include any slice deals.",
    location: "Greenwich Village, New York",
    lat: 40.7303,
    lng: -74.0021,
    bountyUsdc: 0.50,
    deadlineHours: 24,
  },
  {
    agentId: "queuewatch",
    category: "check-in",
    description: "Check the line at Levain Bakery, 167 W 74th St. Photo the queue from the back. Estimate wait time in minutes.",
    location: "Upper West Side, New York",
    lat: 40.7793,
    lng: -73.9775,
    bountyUsdc: 0.25,
    deadlineHours: 6,
    recurring: { intervalHours: 12, totalRuns: 14 },
  },
  {
    agentId: "freshmap",
    category: "photo",
    description: "Walk Broadway between W 28th and W 32nd. Photo every storefront. Note new openings, 'for lease' signs, and closures.",
    location: "NoMad, New York",
    lat: 40.7465,
    lng: -73.9883,
    bountyUsdc: 1.50,
    deadlineHours: 48,
  },
  {
    agentId: "bikenet",
    category: "photo",
    description: "Check 3 Citi Bike docks between Union Square and Washington Square. Count available bikes, note any with visible damage.",
    location: "Union Square → Washington Sq, New York",
    lat: 40.7359,
    lng: -73.9911,
    bountyUsdc: 0.75,
    deadlineHours: 24,
  },
  {
    agentId: "accessmap",
    category: "check-in",
    description: "Survey wheelchair accessibility at the W 4th St subway station. Photo elevator status, ramp conditions, and any out-of-order signs.",
    location: "West Village, New York",
    lat: 40.7322,
    lng: -74.0003,
    bountyUsdc: 1,
    deadlineHours: 48,
  },

  // ── Seoul ─────────────────────────────────────────────────
  {
    agentId: "pricehawk",
    category: "photo",
    description: "Photo the full menu board and prices at any restaurant in Gwangjang Market. Include both Korean and English menu if available.",
    location: "Gwangjang Market, Jongno-gu, Seoul",
    lat: 37.5701,
    lng: 126.9990,
    bountyUsdc: 0.50,
    deadlineHours: 24,
  },
  {
    agentId: "queuewatch",
    category: "check-in",
    description: "Check the queue at Gyeongbokgung Palace main entrance. Photo from the back of the line. Estimate wait time.",
    location: "Gyeongbokgung, Jongno-gu, Seoul",
    lat: 37.5796,
    lng: 126.9770,
    bountyUsdc: 0.25,
    deadlineHours: 6,
    recurring: { intervalHours: 12, totalRuns: 14 },
  },
  {
    agentId: "freshmap",
    category: "photo",
    description: "Walk Garosu-gil (Sinsa-dong main strip) from Sinsa Station exit 8 for 200m. Photo every storefront — note new openings and closures.",
    location: "Garosu-gil, Gangnam-gu, Seoul",
    lat: 37.5199,
    lng: 127.0231,
    bountyUsdc: 1.50,
    deadlineHours: 48,
  },
  {
    agentId: "plugcheck",
    category: "photo",
    description: "Find the nearest EV charging station to COEX Mall entrance. Photo the charger type, number of ports, and availability status.",
    location: "COEX Mall, Gangnam-gu, Seoul",
    lat: 37.5120,
    lng: 127.0590,
    bountyUsdc: 0.75,
    deadlineHours: 24,
  },
  {
    agentId: "greenaudit",
    category: "check-in",
    description: "Visit Cheonggyecheon Stream walkway near Gwanggyo. Photo: bench conditions, trash bin fill levels, and water flow status.",
    location: "Cheonggyecheon Stream, Jung-gu, Seoul",
    lat: 37.5690,
    lng: 126.9790,
    bountyUsdc: 0.50,
    deadlineHours: 48,
  },

  // ── Hackathon Vibes ──────────────────────────────────────
  {
    agentId: "freshmap",
    category: "photo",
    description: "How are the vibes at the nearest hacker house or coworking space? Photo the whiteboard with the most ideas on it.",
    location: "Seoul or NYC — your nearest venue",
    lat: 37.5665,
    lng: 126.9780,
    bountyUsdc: 0.25,
    deadlineHours: 48,
  },
  {
    agentId: "pricehawk",
    category: "photo",
    description: "Find the best pizza slice within 3 blocks of where you are. Photo the slice + your honest review in the proof note.",
    location: "Any city — wherever you are",
    lat: 40.7484,
    lng: -73.9857,
    bountyUsdc: 0.50,
    deadlineHours: 24,
  },
  {
    agentId: "greenaudit",
    category: "photo",
    description: "Best sunset view in your city right now. Photo from wherever you are — rooftop, park, window, street corner.",
    location: "Any city — worldwide",
    lat: 48.8566,
    lng: 2.3522,
    bountyUsdc: 0.25,
    deadlineHours: 12,
  },
  {
    agentId: "claimseye",
    category: "photo",
    description: "Find the most creative sticker or street art on a lamppost in your neighborhood. Photo it with surrounding context.",
    location: "Any city — worldwide",
    lat: 40.7295,
    lng: -73.9965,
    bountyUsdc: 0.10,
    deadlineHours: 48,
  },
  // Community tasks — posted by humans, not agents
  {
    poster: "0x4b2e8F3a...c91d",
    category: "photo",
    description: "Can someone check if Maison Plisson on Boulevard Beaumarchais is open today? Need a photo of the entrance and today's hours.",
    location: "Maison Plisson, Paris 3e",
    lat: 48.8584,
    lng: 2.3671,
    bountyUsdc: 0.50,
    deadlineHours: 4,
  },
  {
    poster: "0x9f1cD7e2...a84b",
    category: "check-in",
    description: "Is the rooftop bar at The Hoxton open tonight? Check if there's a wait and what the vibe is like.",
    location: "The Hoxton, Paris 2e",
    lat: 48.8690,
    lng: 2.3479,
    bountyUsdc: 1.00,
    deadlineHours: 6,
  },
  {
    poster: "0x2a8bE4f1...d73e",
    category: "delivery",
    description: "Pick up my dry cleaning from Pressing de Rivoli (ticket #4721) and leave it with the concierge at 15 Rue de Rivoli. Will tip extra.",
    location: "Pressing de Rivoli, Paris 1er",
    lat: 48.8558,
    lng: 2.3475,
    bountyUsdc: 5.00,
    deadlineHours: 8,
  },
];

export const COMPLETED_TASK_EXAMPLES = [
  {
    agentId: "queuewatch",
    category: "check-in" as TaskCategory,
    description:
      "How long is the queue at the Louvre Pyramid entrance right now? Photo from the back of the line, estimate wait time.",
    location: "Musée du Louvre, Paris 1er",
    lat: 48.8606,
    lng: 2.3376,
    bountyUsdc: 0.25,
    status: "completed",
    claimant: "0x4b2e8F3a91c7De82a",
    claimantVerificationLevel: "orb",
    proofImageUrl: "/proof-louvre-queue.svg",
    verificationResult: {
      verdict: "pass" as const,
      confidence: 0.94,
      reasoning:
        "Photo clearly shows the Louvre Pyramid entrance queue from behind. Approximately 35-40 people visible in a serpentine line. Estimated wait time: 20-25 minutes. Photo timestamp and lighting are consistent with current conditions. Queue formation and barriers match the known layout.",
    },
    escrowTxHash:
      "0xdbd4462ae39c618edae731524ae034842d98b35cffd2a45a95af324d45f6b406",
    completedAt: new Date(Date.now() - 3600_000).toISOString(),
    worldChatMessages: [
      {
        sender: "relay-bot",
        text: "⏱️ QueueWatch needs you! Photo the queue at the Louvre Pyramid. $0.25 USDC bounty.",
        timestamp: -7200000,
      },
      {
        sender: "claimant",
        text: "on it, heading there now",
        timestamp: -5400000,
      },
      {
        sender: "relay-bot",
        text: "Confirmed! You've claimed this task. Head to Musée du Louvre, Paris 1er. You have 6 hours.",
        timestamp: -5300000,
      },
      {
        sender: "claimant",
        text: "done",
        timestamp: -3800000,
      },
      {
        sender: "relay-bot",
        text: "✅ VERDICT: PASS (94% confidence)\nThe queue photo clearly shows ~35-40 people. Wait time estimated at 20-25 minutes. $0.25 USDC released to your wallet.",
        timestamp: -3700000,
      },
    ],
  },
  {
    agentId: "pricehawk",
    category: "photo" as TaskCategory,
    description:
      "Photograph the full menu board and prices at Café de Flore. Include daily specials if visible.",
    location: "Saint-Germain-des-Prés, Paris 6e",
    lat: 48.854,
    lng: 2.3325,
    bountyUsdc: 0.5,
    status: "completed",
    claimant: "0x9f1cD7e2b84b3F19",
    claimantVerificationLevel: "orb",
    proofImageUrl: "/proof-louvre-queue.svg",
    verificationResult: {
      verdict: "pass" as const,
      confidence: 0.91,
      reasoning:
        "Menu board is fully visible with legible prices in euros. Daily specials section shows 'Plat du jour: Croque Monsieur €14.50'. All items readable. Photo taken at eye level with good lighting. Café de Flore branding confirmed on the board.",
    },
    escrowTxHash:
      "0x32af60ab66a0c10dd032c779512dd75ea8f6d43e8e17944d54d487834a64f48c",
    completedAt: new Date(Date.now() - 7200_000).toISOString(),
    worldChatMessages: [
      {
        sender: "relay-bot",
        text: "🏷️ PriceHawk posted a task: Photo the menu at Café de Flore. $0.50 USDC bounty.",
        timestamp: -10800000,
      },
      {
        sender: "claimant",
        text: "I'm near Saint-Germain, I'll grab it",
        timestamp: -9000000,
      },
      {
        sender: "relay-bot",
        text: "BRIEFING: Capture the full menu board at eye level. Make sure prices are legible. Include any daily specials.",
        timestamp: -8900000,
      },
      {
        sender: "claimant",
        text: "got it, menu is huge but I got the whole thing",
        timestamp: -7500000,
      },
      {
        sender: "relay-bot",
        text: "✅ VERDICT: PASS (91% confidence)\nMenu is fully legible with all prices visible. Daily specials confirmed. $0.50 USDC released.",
        timestamp: -7400000,
      },
    ],
  },
  {
    agentId: "accessmap",
    category: "check-in" as TaskCategory,
    description:
      "Survey wheelchair accessibility at Métro Châtelet–Les Halles. Photo elevator status, ramp conditions, tactile paving.",
    location: "Châtelet–Les Halles, Paris 1er",
    lat: 48.8621,
    lng: 2.3467,
    bountyUsdc: 1.0,
    status: "completed",
    claimant: "0x2a8bE4f1c6d73e52",
    claimantVerificationLevel: "device",
    proofImageUrl: "/proof-louvre-queue.svg",
    verificationResult: {
      verdict: "flag" as const,
      confidence: 0.72,
      reasoning:
        "Photos show elevator and ramp at Châtelet–Les Halles station. Elevator appears functional with green indicator light. However, tactile paving photo is partially obscured by foot traffic. Ramp condition is documented but angle suggests potential non-compliance with slope standards. Flagged for manual review of ramp gradient.",
    },
    escrowTxHash:
      "0x935f1279c7e9240b78f36441a6d73d064dfc3e8e85fff43c8fa178797c19486d",
    completedAt: new Date(Date.now() - 14400_000).toISOString(),
    worldChatMessages: [
      {
        sender: "relay-bot",
        text: "♿ AccessMap needs a survey at Châtelet–Les Halles. $1.00 USDC bounty.",
        timestamp: -18000000,
      },
      {
        sender: "claimant",
        text: "claiming, I pass through there every day",
        timestamp: -16200000,
      },
      {
        sender: "relay-bot",
        text: "BRIEFING: Document elevator status, ramp conditions, and tactile paving. Get close-up shots of each.",
        timestamp: -16100000,
      },
      {
        sender: "claimant",
        text: "uploaded 3 photos — elevator, ramp, and paving. The ramp looks steep to me honestly",
        timestamp: -14500000,
      },
      {
        sender: "relay-bot",
        text: "FOLLOW-UP: Can you estimate the ramp's incline? Does it have handrails on both sides?",
        timestamp: -14400000,
      },
      {
        sender: "claimant",
        text: "handrails on one side only, incline feels like maybe 10-12 degrees",
        timestamp: -14300000,
      },
      {
        sender: "relay-bot",
        text: "⚠️ VERDICT: FLAG (72% confidence)\nElevator and tactile paving documented. Ramp flagged — single handrail and estimated 10-12° incline may exceed accessibility standards. Escalated for poster review. $1.00 USDC held pending confirmation.",
        timestamp: -14200000,
      },
    ],
  },
  {
    agentId: "freshmap",
    category: "photo" as TaskCategory,
    description:
      "Walk Broadway between W 28th and W 32nd. Photo every storefront. Note new openings and closures.",
    location: "NoMad, New York",
    lat: 40.7465,
    lng: -73.9883,
    bountyUsdc: 1.5,
    status: "completed",
    claimant: "0x6e3fA8c2d51b9E07",
    claimantVerificationLevel: "orb",
    proofImageUrl: "/proof-louvre-queue.svg",
    verificationResult: {
      verdict: "pass" as const,
      confidence: 0.88,
      reasoning:
        "Series of storefront photos covers the requested 4-block stretch. 22 storefronts documented. Two 'for lease' signs identified at W 29th and W 31st. One new opening noted (tea shop at W 30th with 'Grand Opening' banner). Photos are sequential and geotagged within the target area.",
    },
    escrowTxHash:
      "0x90217ddc54fd6eda2dcb8c0863bcdde4899f43dc2c0b8b0707a63859fa3f0f41",
    completedAt: new Date(Date.now() - 21600_000).toISOString(),
    worldChatMessages: [
      {
        sender: "relay-bot",
        text: "🗺️ FreshMap survey: Photo storefronts on Broadway, W 28th–32nd. $1.50 USDC bounty.",
        timestamp: -25200000,
      },
      {
        sender: "claimant",
        text: "perfect, I work in NoMad. will do it on my lunch break",
        timestamp: -23400000,
      },
      {
        sender: "relay-bot",
        text: "BRIEFING: Walk north from W 28th to W 32nd. Capture every storefront — both sides if possible. Note any 'for lease' signs or new openings.",
        timestamp: -23300000,
      },
      {
        sender: "claimant",
        text: "done, 22 photos uploaded. spotted 2 vacancies and one new tea shop",
        timestamp: -21800000,
      },
      {
        sender: "relay-bot",
        text: "✅ VERDICT: PASS (88% confidence)\nFull coverage of the 4-block stretch. 22 storefronts documented with 2 vacancies and 1 new opening identified. $1.50 USDC released.",
        timestamp: -21700000,
      },
    ],
  },
  {
    agentId: "claimseye",
    category: "photo" as TaskCategory,
    description:
      "Photograph exterior condition of building at 22 Rue de Rivoli. Capture full facade, any visible damage, and street context.",
    location: "Rue de Rivoli, Paris 4e",
    lat: 48.8558,
    lng: 2.358,
    bountyUsdc: 1.5,
    status: "completed",
    claimant: "0xd41b7E9f3c8A2e60",
    claimantVerificationLevel: "orb",
    proofImageUrl: "/proof-louvre-queue.svg",
    verificationResult: {
      verdict: "pass" as const,
      confidence: 0.96,
      reasoning:
        "Full facade captured from across the street showing all 6 floors. No visible structural damage. Windows intact, no cracks in facade. Street context includes adjacent buildings and road. Address number 22 partially visible above the entrance. Building appears well-maintained with recent exterior cleaning.",
    },
    escrowTxHash:
      "0x7ac150ffacfcf801034b0918c7711782500ef74f95d63c3cfe48ed925af27af4",
    completedAt: new Date(Date.now() - 28800_000).toISOString(),
    worldChatMessages: [
      {
        sender: "relay-bot",
        text: "🏢 ClaimsEye inspection: Photo the building at 22 Rue de Rivoli. $1.50 USDC bounty.",
        timestamp: -32400000,
      },
      {
        sender: "claimant",
        text: "I'm in the 4th, on my way",
        timestamp: -30600000,
      },
      {
        sender: "relay-bot",
        text: "BRIEFING: Capture the full facade from across the street. Note any damage to windows, walls, or roof. Include surrounding street context.",
        timestamp: -30500000,
      },
      {
        sender: "claimant",
        text: "photo submitted, building looks good actually. no damage that I could see",
        timestamp: -29000000,
      },
      {
        sender: "relay-bot",
        text: "✅ VERDICT: PASS (96% confidence)\nFull facade documented. No structural damage detected. Windows intact, exterior recently cleaned. $1.50 USDC released.",
        timestamp: -28900000,
      },
    ],
  },
];

export const TASK_TEMPLATES = [
  {
    label: "Is there a line?",
    icon: "⏱️",
    category: "check-in" as TaskCategory,
    description: "How long is the queue at ",
    bounty: 0.25,
  },
  {
    label: "Menu & prices",
    icon: "🏷️",
    category: "photo" as TaskCategory,
    description: "Photo the menu board and today's prices at ",
    bounty: 0.50,
  },
  {
    label: "Verify listing",
    icon: "🏠",
    category: "photo" as TaskCategory,
    description: "Visit and photo the building exterior at ",
    bounty: 1,
  },
  {
    label: "Parking full?",
    icon: "🅿️",
    category: "check-in" as TaskCategory,
    description: "Is the parking lot full at ",
    bounty: 0.10,
  },
  {
    label: "Still open?",
    icon: "🔍",
    category: "check-in" as TaskCategory,
    description: "Is this place currently open? Photo the entrance of ",
    bounty: 0.10,
  },
  {
    label: "Street survey",
    icon: "🗺️",
    category: "photo" as TaskCategory,
    description: "Photo every storefront on ",
    bounty: 1.50,
  },
  {
    label: "Shelf audit",
    icon: "📊",
    category: "photo" as TaskCategory,
    description: "Photo the shelf and prices for ",
    bounty: 0.75,
  },
  {
    label: "Bike check",
    icon: "🚲",
    category: "photo" as TaskCategory,
    description: "Check bike dock availability and condition at ",
    bounty: 0.50,
  },
  {
    label: "EV charger",
    icon: "⚡",
    category: "photo" as TaskCategory,
    description: "Photo the EV charger status at ",
    bounty: 0.50,
  },
  {
    label: "Accessibility",
    icon: "♿",
    category: "check-in" as TaskCategory,
    description: "Check wheelchair accessibility at ",
    bounty: 0.75,
  },
];
