import { NextRequest, NextResponse } from "next/server";
import { ensurePromptFor } from "@/lib/daily-generator";
import { utcDate } from "@/lib/daily";

// Writes TOMORROW's top favour, and backfills today's if it is somehow missing.
//
// Runs ahead of the UTC rollover so the question is always waiting rather than
// being generated by the first person to open the app at 00:00. If generation
// fails for any reason the gate still opens on the deterministic pool — see
// lib/daily-generator, every path falls back.
export async function GET(req: NextRequest) {
  if (req.headers.get("authorization") !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const today = utcDate(Date.now());
  const tomorrow = utcDate(Date.now() + 86400_000);

  const results = {
    today: await ensurePromptFor(today),
    tomorrow: await ensurePromptFor(tomorrow),
  };

  return NextResponse.json({ ok: true, ...results });
}
