import { NextRequest, NextResponse } from "next/server";
import { ensurePromptFor } from "@/lib/daily-generator";
import { utcDate } from "@/lib/daily";
import { runDailyNotifyPass } from "@/lib/daily-notify";

// Writes TOMORROW's top favour, and backfills today's if it is somehow missing.
//
// Runs ahead of the UTC rollover so the question is always waiting rather than
// being generated by the first person to open the app at 00:00. If generation
// fails for any reason the gate still opens on the deterministic pool — see
// lib/daily-generator, every path falls back.
export async function GET(req: NextRequest) {
  if (req.headers.get("authorization") !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const today = utcDate(Date.now());
  const tomorrow = utcDate(Date.now() + 86400_000);

  const results = {
    today: await ensurePromptFor(today),
    tomorrow: await ensurePromptFor(tomorrow),
  };

  // Comeback notifications ride the same cron. Dark until DAILY_NOTIFY_ENFORCE
  // is flipped; deduped per pass per day, so the two cron entries (morning +
  // 22:00 UTC) can never double-send. A notify failure never fails the cron —
  // the prompts above are the part the gate depends on.
  const notify = await runDailyNotifyPass(Date.now()).catch((e) => {
    console.error("[Cron] daily notify pass failed:", e);
    return { error: String(e) };
  });

  return NextResponse.json({ ok: true, ...results, notify });
}
